Added properties of bodies and fixed an error in "area_of_circle"
KGB33/MathTools pull request #16
Opened 2020-08-28 02:29 UTC by dweiss2

I added a file to the geometry tools to calculate section modulus (and other properties) of bodies. These include rectangular bars, round bars, T sections, and I sections. 

Lastly I noticed that the area_of_circle function allowed for complex numbers but was not correctly calculating the area of a circle in the complex plane. The correct radius for a complex radius is the complex modulus of the radius (i.e. radius = a + bi = [a^2 + b^2]^(1/2)).

2020-08-28 17:24 UTC, KGB33 requested changes
Some of your doctests are failing.  You can use 
```
python -m doctest mttools/geometry_tools/PropertiesOfBodies.py -o NORMALIZE_WHITESPACE
```

To run the doctests for your file. 

Also, are there any properties you could test for?

2020-08-28 17:24 UTC, KGB33 commented on mttools/geometry_tools/__init__.py
> +from .PropertiesOfBodies import (
I would like users to import the functions from the `PropertiesOfBodies` file. This adds more information when importing and follows the same practice and the rest of the `foo_tools` sections.

2020-08-29 04:13 UTC, KGB33 commented
Just a heads up there's a problem with `black`'s stable branch that the new CodeQuality action I added. If it's not fixed by the time you resubmit that'll be fine I'll merge it anyways.

2020-09-03 01:02 UTC, dweiss2 commented on mttools/geometry_tools/PropertiesOfBodies.py
> +def rect_bar(depth: RealNumber, thickness: RealNumber) -> dict:
Done. The centroid is now 2 keys, Centroid X and Centroid Y

2020-09-03 01:04 UTC, dweiss2 commented
> 
> 
> Some of your doctests are failing. You can use
> 
> ```
> python -m doctest mttools/geometry_tools/PropertiesOfBodies.py -o NORMALIZE_WHITESPACE
> ```
> 
> To run the doctests for your file.
> 
> Also, are there any properties you could test for?

What do you mean about properties I can test for? Do you mean other properties of the section itself?

2020-09-03 03:16 UTC, KGB33 commented
> What do you mean about properties I can test for? Do you mean other properties of the section itself?

Is there anything that's true for every possible body? 

For example, for every triangle, the angles always add up to 180degrees.

2020-09-04 15:01 UTC, dweiss2 commented
I can't think of anything that could be checked this way. All of these are just cross-sections of solid bodies.

2020-09-04 15:48 UTC, merged

2020-09-04 15:48 UTC, KGB33 commented
Awesome! Thanks for the PR